window.tailwind = window.tailwind || {};
window.tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "secondary-fixed-dim": "#c2c7cc",
                "surface": "#f9f9f9",
                "tertiary": "#2c2c2c",
                "on-secondary-container": "#5e6368",
                "surface-gray": "#F7FAFC",
                "surface-variant": "#e2e2e2",
                "surface-container-highest": "#e2e2e2",
                "on-primary-fixed": "#410000",
                "outline-variant": "#e3beb8",
                "on-error-container": "#93000a",
                "background": "#f9f9f9",
                "inverse-surface": "#2f3131",
                "error": "#ba1a1a",
                "surface-bright": "#f9f9f9",
                "on-secondary-fixed-variant": "#42474c",
                "primary": "#610000",
                "surface-tint": "#b52619",
                "surface-container": "#eeeeee",
                "inverse-on-surface": "#f0f1f1",
                "secondary-container": "#dbe0e5",
                "on-background": "#1a1c1c",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#920703",
                "primary-fixed": "#ffdad4",
                "on-surface-variant": "#5a403c",
                "tertiary-fixed-dim": "#c6c6c6",
                "error-container": "#ffdad6",
                "secondary": "#595f63",
                "on-primary-container": "#ff907f",
                "inverse-primary": "#ffb4a8",
                "on-secondary-fixed": "#171c20",
                "on-tertiary-fixed": "#1b1b1b",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "on-tertiary-container": "#afafaf",
                "primary-container": "#8b0000",
                "secondary-fixed": "#dee3e8",
                "on-tertiary": "#ffffff",
                "tertiary-fixed": "#e2e2e2",
                "deep-maroon": "#8B0000",
                "on-tertiary-fixed-variant": "#474747",
                "tertiary-container": "#424242",
                "on-surface": "#1a1c1c",
                "on-secondary": "#ffffff",
                "surface-container-high": "#e8e8e8",
                "border-muted": "#CBD5E0",
                "text-primary": "#1A202C",
                "primary-fixed-dim": "#ffb4a8",
                "surface-dim": "#dadada",
                "outline": "#8e706b",
                "surface-container-low": "#f3f3f4"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-md": "16px",
                "margin-mobile": "16px",
                "stack-lg": "32px",
                "stack-sm": "8px",
                "margin-desktop": "40px",
                "container-max": "1280px",
                "gutter": "24px",
                "section-gap": "80px"
            },
            "fontFamily": {
                "headline-lg-mobile": ["Poppins"],
                "body-md": ["Poppins"],
                "headline-lg": ["Poppins"],
                "headline-md": ["Poppins"],
                "display-lg": ["Poppins"],
                "body-lg": ["Poppins"],
                "caption": ["Poppins"],
                "label-md": ["Poppins"]
            },
            "fontSize": {
                "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "caption": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }]
            }
        },
    },
};